### ISSUE TITLE
How do I use this on the client-side?

### ISSUE THREAD

**Issue by rkagerer** [warren-bank/ethereumjs-tx-unsign#1]
I want to make a very simple little webpage that uses your module to decode a signed Ethereum transaction (similar to https://blockchain.info/decode-tx)

I'm playing around on repl.it and trying `require('ethereumjs-tx-unsign')` but it complains it can't find the module.  When I try to fetch it via browserify at https://wzrd.in/ it also fails; (maybe because you're github repository is missing a "latest" tag?)

**Comment by warren-bank** [comment]
I'll be honest, I didn't bother to make a browser build for this library.
It would be easy enough to do; personally, I prefer Webpack.. but Browserify would work too.

Until that happens, your best bet would be to use this project's big brother..
which does include a browser build that's ready to use:

[git repo: "ethereumjs-tx-sign"](https://github.com/warren-bank/ethereumjs-tx-sign)

[browser bundle](https://github.com/warren-bank/ethereumjs-tx-sign/raw/master/browser-build/dist/js/bundle.js)

The README in the git repo lists what global variables the bundle adds to `window`. But essentially:

```text
<script src="https://rawgit.com/warren-bank/ethereumjs-tx-sign/master/browser-build/dist/js/bundle.js"></script>
<script>
const {unsign} = window.ethereumjs_tx_sign

{
  let rawTx = 'f874808506fc23ac008227108080a47f746573743200000000000000000000000000000000000000000000000000000060005725a0fbbabeb385a5419062514db3fe85810876cdc4608cc9df11620a5a5c4dcdf149a010b15babddb17af1b970b6ed47a4f47b60e4a95ffd95842059977c76510038e0'

  let {txData, signature, msgHash, publicKey, address} = unsign(rawTx)

  console.log('txData:', txData)
}
</script>
```

**Comment by warren-bank** [comment]
If 220 KB is too big and you want the smaller.. leaner.. no frills version, then let me know and I'll package up a browser build for you.. it really wouldn't take more than a few minutes. Just let me know.

**Comment by rkagerer** [comment]
Thanks for the offer!  At the moment I'd be happy to just get a barebones unsign(blah) working in repl.it.

**Comment by rkagerer** [comment]
Thanks no worries your sample code is precisely what I needed!

**Comment by rkagerer** [comment]
If anyone stumbles on this in the future here's a quick and dirty prototype https://rkagerer.github.io/DecodeEthTxn/
